[package]
name = "connect_four"
version = "0.3.0"
edition = "2021"

[lib]
name = "connect_four"
path = "src/lib.rs"

[[bench]]
name = "benchmark"
harness = false

[dependencies]

[dev-dependencies]
criterion = "0.5.1"
